title = "Livermore Hub"
document_type = "Control Narrative"
issuing_dept = "Systems Engineering Department"
operational_scope = "LIV"
system_scope = "CTRL"
iec_61355_type = "EFE"
doc_num = "CN1"
creator= "Remi Godin"
approver= ""
owner= "True Zero"

[[scope]]
name = "==LIV"
desc = "The Livermore HUB site. Includes the fueling operations and testing operations. When referencing this scope, this covers the station as a whole."

[[scope]]
name = "=CTRL"
desc = "This scope refers to the overall control of the site, and includes all systems and sub-systems."

[[scope]]
name = "=DB"
desc = "This scope refers to main FEF database."

[[scope]]
name = "=FEF"
desc = "This scope includes all operations from the NX102 PLC, and all balance-of-plant items that are controlled by FEF."

[[scope]]
name = "=IPC"
desc = "This scope refers to the FEF industrial PC running the DAQ software."

[[scope]]
name = "=DAQ"
desc = "This scope refers to the data acquisition functionality of the system."

[[scope]]
name = "=BOSCH"
desc = "This scope includes all Bosch items."

[[scope]]
name = "=MHI"
desc = "This scope includes all MHI items."

[[scope]]
name = "=EBARA"
desc = "This scope includes all Ebara items."

[[scope]]
name = "=NIKK"
desc = "This scope includes all Nikkiso items."

[[scope]]
name = "=TMS"
desc = "This scope includes all thermal management items."

[[product]]
name = "-CN"
desc = "Defines a control narrative."

[[product]]
name = "-SEQ"
desc = "Defines a sequence of operation."

[[product]]
name = "-DES"
desc = "Defines a system design."

[[product]]
name = "-SPEC"
desc = "Defines a specification, framework, or other abstraction."
