title = "Livermore Hub"
document_type = "Control Narrative"
issuing_dept = "Systems Engineering Department"
operational_scope = "LIV"
system_scope = "CTRL"
iec_61355_type = "EFE"
doc_num = "1"
creator= "Remi Godin"
approver= ""
owner= "True Zero"
